import { Type, type Static } from "@sinclair/typebox";
import { type StyleRules, ruleHandle } from "./utils";

export const LayoutProps = Type.Object({
    row: Type.Optional(Type.Boolean()),
    col: Type.Optional(Type.Boolean()),
    justifyStart: Type.Optional(Type.Boolean()),
    jStart: Type.Optional(Type.Boolean()),
    justifyEnd: Type.Optional(Type.Boolean()),
    jEnd: Type.Optional(Type.Boolean()),
    justifyCenter: Type.Optional(Type.Boolean()),
    jCenter: Type.Optional(Type.Boolean()),
    justifyBetween: Type.Optional(Type.Boolean()),
    jBetween: Type.Optional(Type.Boolean()),
    justifyAround: Type.Optional(Type.Boolean()),
    jAround: Type.Optional(Type.Boolean()),
    justifyEvenly: Type.Optional(Type.Boolean()),
    jEvenly: Type.Optional(Type.Boolean()),
    itemStart: Type.Optional(Type.Boolean()),
    iStart: Type.Optional(Type.Boolean()),
    itemEnd: Type.Optional(Type.Boolean()),
    iEnd: Type.Optional(Type.Boolean()),
    itemCenter: Type.Optional(Type.Boolean()),
    iCenter: Type.Optional(Type.Boolean()),
    itemStretch: Type.Optional(Type.Boolean()),
    iStretch: Type.Optional(Type.Boolean()),
    itemBaseline: Type.Optional(Type.Boolean()),
    iBaseline: Type.Optional(Type.Boolean()),
    wrap: Type.Optional(Type.Boolean()),
    wrapReverse: Type.Optional(Type.Boolean()),
    flex: Type.Optional(Type.Number()),
});

export type LayoutProps = Static<typeof LayoutProps>;

export const layoutRules: StyleRules<LayoutProps> = {
    row: [ruleHandle("display", v => v ? "flex" : ""), ruleHandle("flex-direction", v => v ? "row" : "")],
    col: [ruleHandle("display", v => v ? "flex" : ""), ruleHandle("flex-direction", v => v ? "column" : "")],
    justifyStart: [ruleHandle("justify-content", v => v ? "flex-start" : "")],
    jStart: [ruleHandle("justify-content", v => v ? "flex-start" : "")],
    justifyEnd: [ruleHandle("justify-content", v => v ? "flex-end" : "")],
    jEnd: [ruleHandle("justify-content", v => v ? "flex-end" : "")],
    justifyCenter: [ruleHandle("justify-content", v => v ? "center" : "")],
    jCenter: [ruleHandle("justify-content", v => v ? "center" : "")],
    justifyBetween: [ruleHandle("justify-content", v => v ? "space-between" : "")],
    jBetween: [ruleHandle("justify-content", v => v ? "space-between" : "")],
    justifyAround: [ruleHandle("justify-content", v => v ? "space-around" : "")],
    jAround: [ruleHandle("justify-content", v => v ? "space-around" : "")],
    justifyEvenly: [ruleHandle("justify-content", v => v ? "space-evenly" : "")],
    jEvenly: [ruleHandle("justify-content", v => v ? "space-evenly" : "")],
    itemStart: [ruleHandle("align-items", v => v ? "flex-start" : "")],
    iStart: [ruleHandle("align-items", v => v ? "flex-start" : "")],
    itemEnd: [ruleHandle("align-items", v => v ? "flex-end" : "")],
    iEnd: [ruleHandle("align-items", v => v ? "flex-end" : "")],
    itemCenter: [ruleHandle("align-items", v => v ? "center" : "")],
    iCenter: [ruleHandle("align-items", v => v ? "center" : "")],
    itemStretch: [ruleHandle("align-items", v => v ? "stretch" : "")],
    iStretch: [ruleHandle("align-items", v => v ? "stretch" : "")],
    itemBaseline: [ruleHandle("align-items", v => v ? "baseline" : "")],
    iBaseline: [ruleHandle("align-items", v => v ? "baseline" : "")],
    wrap: [ruleHandle("flex-wrap", v => v ? "wrap" : "")],
    wrapReverse: [ruleHandle("flex-wrap", v => v ? "wrap-reverse" : "")],
    flex: [ruleHandle("flex", v => v ? v : "")],
};
